### ISSUE TITLE
file manager issue

### ISSUE THREAD

**Issue by sparta3407** [hussein-aitlahcen/BlackHole#5]
salam, first thanks for this great rat,but when i upload a file in the target machine , the function execute does not work , fix it please

**Comment by hussein-aitlahcen** [comment]
fix it yourself

**Comment by sparta3407** [comment]
are you angry !!

**Comment by s1st3r** [comment]
Hahaha, some people with crazy questions!!!!

**Comment by ghost** [comment]
fuck your stupid RAT anyway
